### ISSUE TITLE
PHP Fatal error:  Uncaught Twig_Error_Syntax: Unknown "bem" function in "{% set grid_base_class = grid_base_class|default('grid') %}

### ISSUE THREAD

**Issue by SuperNami** [fourkitchens/emulsify#168]
First time using emulsify, running npm start returns error. Binary versions:
npm 5.4.2
node 8.8.1

```
npm start

> emulsify@1.0.0 start /home/ubuntu/workspace/web/themes/custom/emulsify
> gulp clean && gulp compile && gulp theme

[13:17:33] Using gulpfile ~/workspace/web/themes/custom/emulsify/gulpfile.js
[13:17:33] Starting 'clean:css'...
[13:17:33] Finished 'clean:css' after 6.47 ms
[13:17:33] Starting 'clean'...
[13:17:33] Finished 'clean' after 27 μs
[13:17:36] Using gulpfile ~/workspace/web/themes/custom/emulsify/gulpfile.js
[13:17:36] Starting 'icons'...
[13:17:36] Finished 'icons' after 14 ms
[13:17:36] Starting 'pl:scss-to-yaml'...
[13:17:36] Finished 'pl:scss-to-yaml' after 4.18 ms
[13:17:36] Starting 'pl:full'...
configuring pattern lab...
PHP Fatal error:  Uncaught Twig_Error_Syntax: Unknown "bem" function in "{% set grid_base_class = grid_base_class|default('grid') %}

{% if grid_label %}
  {% include "@atoms/02-text/00-headings/_heading.twig" with {
    "heading_level": 2,
    "heading": grid_label,
  } %}
{% endif %}
<div {{ bem(grid_base_class, (grid_modifiers), grid_blockname) }}>
  {% block grid_content %}
    {% for item in items %}
      <div class="grid__item">{{ item }}</div>
    {% endfor %}
  {% endblock %}
</div>
" at line 9. in /home/ubuntu/workspace/web/themes/custom/emulsify/pattern-lab/vendor/twig/twig/lib/Twig/ExpressionParser.php:665
Stack trace:
#0 /home/ubuntu/workspace/web/themes/custom/emulsify/pattern-lab/vendor/twig/twig/lib/Twig/ExpressionParser.php(374): Twig_ExpressionParser->getFunctionNodeClass('bem', 9)
#1 /home/ubuntu/workspace/web/themes/custom/emulsify/pattern-lab/vendor/twig/twig/lib/Twig/ExpressionParser.php(162): Twig_ExpressionParser->getFunctionNode('bem', 9)
#2 /home/ubuntu/workspace/web/themes/custom/emulsify/pattern-lab in /home/ubuntu/workspace/web/themes/custom/emulsify/pattern-lab/vendor/twig/twig/lib/Twig/ExpressionParser.php on line 665
Error with code 255 after running: php pattern-lab/core/console --generate
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! emulsify@1.0.0 start: `gulp clean && gulp compile && gulp theme`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the emulsify@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-10-30T13_17_36_254Z-debug.log
```

**Comment by ccjjmartin** [comment]
@SuperNami The bem function is separate from the Emulsify repo and is installed during the installation process.  Did you get any errors during your install?

**Comment by ccjjmartin** [comment]
@SuperNami: It looks like we moved this over to the `composer install` process:
https://github.com/fourkitchens/emulsify/blob/develop/composer.json#L34

**Comment by SuperNami** [comment]
I did, I could not run "composer create-project -n pattern-lab/edition-twig-standard pattern-lab" because of git clone issue.

And now when trying to recreate I'm getting this:

```
npm start

> emulsify@1.0.0 start /home/ubuntu/workspace/web/themes/custom/emulsify
> gulp clean && gulp compile && gulp theme

fs.js:648
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './pattern-lab/config/config.yml'
    at Object.fs.openSync (fs.js:648:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at module.exports (/home/ubuntu/workspace/web/themes/custom/emulsify/node_modules/emulsify-gulp/gulp-tasks/gulp-pattern-lab.js:12:10)
    at module.exports (/home/ubuntu/workspace/web/themes/custom/emulsify/node_modules/emulsify-gulp/index.js:95:46)
    at /home/ubuntu/workspace/web/themes/custom/emulsify/gulpfile.js:18:27
    at Object.<anonymous> (/home/ubuntu/workspace/web/themes/custom/emulsify/gulpfile.js:20:3)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! emulsify@1.0.0 start: `gulp clean && gulp compile && gulp theme`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the emulsify@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-10-30T13_30_54_127Z-debug.log
```

Thanks for quick support, I'll try composer install.

**Comment by SuperNami** [comment]
Oh I see why, because I temporarily delete pattern-lab folder, dismiss last error.

**Comment by evanmwillhite** [comment]
Closing as I think this is resolved. Feel free to reopen if not. 

Also, for future reference, if commands fail for some reason, the [manual process for installing](https://github.com/fourkitchens/emulsify/wiki/Installation#committing-to-emulsify) is to clone the repo (or if you already have, remove any failed `/node_modules` and/or `/vendor` directories) and then run `composer install` and then `yarn install` (or `npm install`).

**Comment by cristinallamas** [comment]
If i create a clone of emulsify and require it in my project then i get this error as well.

**Comment by dchaffin** [comment]
I'm still having this same issue (Git Bash on Win10). When I walked through the installation process (D8 w/Composer), it failed on `npm install` because (I believe) of the postinstall scripts (re: #283 ). I ran the first one by itself in bash and the manually copied the twig functions (add_attributes.function.php, pl_attach-library.function.php and bem.function.php) from /vendor/drupal-pattern-lab/{folder}/{file} to {theme}/components/_twig-components/functions/

So, it seems like those extensions are in the right place and when I run `npm start` (or if I just run `php pattern-lab/core/console --generate` by itself), I get this message. What am I doing wrong? Thanks!

**Comment by ModulesUnraveled** [comment]
@dchaffin We're tying to add better widows support here: https://github.com/fourkitchens/emulsify/pull/300

You might give that a look if you're still having issues

**Comment by dchaffin** [comment]
@ModulesUnraveled  - Thanks! I'll keep an eye on that. But in the meantime, I've attempted to manually do what twig_functions.sh is supposed to do and I believe I have copied the 3 twig function files to the correct place ({theme}/components/_twig-components/functions/), but I'm still getting this issue. Can you (or anyone) confirm that is where they are supposed to go? Thanks!

**Comment by amazingrando** [comment]
@dchaffin I can confirm that `add_attributes.function.php`, `bem.function.php`, and `pl_attach-library.function.php` go into `$ROOT/themes/custom/$THEME_NAME/components/_twig-components/functions/`

FWIW, I posted instructions that spell everything out as [Installing Emulsify without composer](https://github.com/fourkitchens/emulsify/wiki/Install-without-Composer) in the wiki.

**Comment by seanr** [comment]
I'm running into this trying to deploy to Pantheon via CircleCI.
